[web]
  port = 8910
  apiProxyPath = "https://vibrant-kowalevski-dfc8d7.netlify.app/.netlify/functions"

[api]
  port = 8911
  [api.paths]
  functions = './api/src/functions'
  graphql = './api/src/graphql'
  generated = './api/generated'
